name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pull submodule
      run: git submodule update --init
    - name: create build dir
      run: cmake -E make_directory build
    - name: create build files
      run: cmake -E chdir build cmake ..
    - name: build project
      run: make -C build/ all
    - name: make test
      run: cmake -E chdir build ctest -V
